name 'yourls'
maintainer 'Nick Clark'
maintainer_email 'n.clark@base2services.com'
license 'mit'
description 'Installs/Configures yourls-cookbook'
long_description 'Installs/Configures yourls-cookbook'
version '0.1.0'

depends 'apache2', '~> 3.2.2'
depends 'ark', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'mysql', '~> 7.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'php', '~> 1.9.0'
