default['yourls']['url'] = 'https://github.com/YOURLS/YOURLS/archive/1.7.1.tar.gz'
default['yourls']['path'] = node['apache']['docroot_dir']
default['yourls']['yours_url'] = 'yourls'
default['yourls']['server_name'] = 'yourls'
default['yourls']['document_root'] = '/var/www/html/yourls'
default['yourls']['gmt_offset'] = '10'
default['yourls']['checksum'] = ''
default['apache']['listen'] = [ '*:80' ]
default['yourls']['port'] = '80'
